[package]
name = "rosd_cli"
version = "0.1.0"
authors = ["patricio tula <tula.patricio@gmail.com>"]
edition = "2018"


[[bin]]
name = "rosd"
path = "src/main.rs"
doc = false


[dependencies]
clap = "2.33.3"


[dependencies.rosd]
version = "~0.1.0"
path = "../rosd"
default-features = false
